server:
  host: 0.0.0.0
  port: 3000
swagger:
  title: New Web's Technologies course with NestJS
  description: The Recipe API description
  version: 1.0
  tag: recette
  path: documentation
mongodb:
  uri: mongodb://0.0.0.0:27017/cousinetna
